version: "3.9"
services:
  integrationwebapi:
    container_name: integrationwebapi
    image: lonestarregistry.azurecr.io/rbdms-image:v1
    environment:
      - ConnectionStrings__RBDMSIntegrationServiceConnection=Server=host.docker.internal;Database=Integration;User Id=UserName;Password=Wh@tEverYouW@nt;Trusted_Connection=false;MultipleActiveResultSets=true
    ports:
      - 60014:80
    entrypoint:
      - dotnet
      - Integration.WebAPI.dll
    working_dir: /App/IntegrationWebAPI